import { writeFileSync } from 'node:fs';
import {
  buildLibertiesPacksForGeneration,
  getLibertiesPackAudit,
  getLibertiesPuzzleAudit,
  type LibertiesPuzzle,
  type LibertiesPackGenerationResult,
} from '../src/data/libertiesPuzzles';

const GENERATED_PATH = 'src/data/libertiesPack.generated.ts';
const AUDIT_PATH = 'docs/liberties-pack-audit.md';

function serializePuzzle(puzzle: LibertiesPuzzle): string {
  return JSON.stringify(puzzle, null, 2)
    .replace(/"([a-zA-Z0-9_]+)":/g, '$1:')
    .replace(/\n/g, '\n  ');
}

function serializePuzzleArray(name: string, puzzles: LibertiesPuzzle[]): string {
  const body = puzzles.map((puzzle) => `  ${serializePuzzle(puzzle)}`).join(',\n');
  return [`export const ${name}: LibertiesPuzzle[] = [`, body, '];'].join('\n');
}

function writeGeneratedPack(
  standardPublicPuzzles: LibertiesPuzzle[],
  standardReservePuzzles: LibertiesPuzzle[],
  hardPublicPuzzles: LibertiesPuzzle[],
  hardReservePuzzles: LibertiesPuzzle[]
): void {
  writeFileSync(
    GENERATED_PATH,
    [
      "import type { LibertiesPuzzle } from './libertiesPuzzles';",
      '',
      '// Generated by `npm run build:liberties-pack`.',
      '// Do not edit individual entries by hand; update the generator/audits instead.',
      serializePuzzleArray('generatedLibertiesPack', standardPublicPuzzles),
      '',
      serializePuzzleArray('generatedLibertiesReservePack', standardReservePuzzles),
      '',
      serializePuzzleArray('generatedLibertiesPackHard', hardPublicPuzzles),
      '',
      serializePuzzleArray('generatedLibertiesReservePackHard', hardReservePuzzles),
      '',
    ].join('\n')
  );
}

function getIdOverlapRatio(a: LibertiesPuzzle[], b: LibertiesPuzzle[]): number {
  const left = new Set(a.map((puzzle) => puzzle.id));
  const right = new Set(b.map((puzzle) => puzzle.id));
  const matches = [...left].filter((id) => right.has(id)).length;
  const size = Math.max(1, Math.max(left.size, right.size));
  return matches / size;
}

function getLayoutOverlapCount(a: LibertiesPuzzle[], b: LibertiesPuzzle[]): number {
  const left = new Set(a.map((puzzle) => puzzle.layout.join('/')));
  return b.filter((puzzle) => left.has(puzzle.layout.join('/'))).length;
}

function getCompanionFamily(puzzle: LibertiesPuzzle): string {
  return puzzle.title.split(':')[0]!.trim();
}

function getDominantTerrain(puzzle: LibertiesPuzzle): string {
  return puzzle.terrainArchetypes?.[0] ?? 'none';
}

function companionPairIsDistinct(standard: LibertiesPuzzle, hard: LibertiesPuzzle): boolean {
  return getCompanionFamily(standard) !== getCompanionFamily(hard) && getDominantTerrain(standard) !== getDominantTerrain(hard);
}

function separateHardCompanionCalendar(standardPublic: LibertiesPuzzle[], hardPublic: LibertiesPuzzle[]): LibertiesPuzzle[] {
  const next = [...hardPublic];
  for (let index = 0; index < Math.min(standardPublic.length, next.length); index += 1) {
    const standard = standardPublic[index]!;
    if (companionPairIsDistinct(standard, next[index]!)) continue;
    const swapIndex = next.findIndex((candidate, candidateIndex) => {
      if (candidateIndex <= index) return false;
      if (!companionPairIsDistinct(standard, candidate)) return false;
      const swapStandard = standardPublic[candidateIndex];
      return !swapStandard || companionPairIsDistinct(swapStandard, next[index]!);
    });
    if (swapIndex >= 0) {
      const current = next[index]!;
      next[index] = next[swapIndex]!;
      next[swapIndex] = current;
    }
  }
  return next.map((puzzle, index) => ({ ...puzzle, calendarIndex: index }));
}

function assertHardAndStandardSeparation(
  standardPublicPuzzles: LibertiesPuzzle[],
  standardReservePuzzles: LibertiesPuzzle[],
  hardPublicPuzzles: LibertiesPuzzle[],
  hardReservePuzzles: LibertiesPuzzle[]
): void {
  if (JSON.stringify(standardPublicPuzzles) === JSON.stringify(hardPublicPuzzles)) {
    throw new Error('Generated hard public pack is byte-identical to generated standard public pack');
  }
  if (JSON.stringify(standardReservePuzzles) === JSON.stringify(hardReservePuzzles)) {
    throw new Error('Generated hard reserve pack is byte-identical to generated standard reserve pack');
  }

  const publicOverlap = getIdOverlapRatio(standardPublicPuzzles, hardPublicPuzzles);
  const reserveOverlap = getIdOverlapRatio(standardReservePuzzles, hardReservePuzzles);
  const publicLayoutOverlap = getLayoutOverlapCount(standardPublicPuzzles, hardPublicPuzzles);
  if (publicOverlap > 0 || publicLayoutOverlap > 0 || reserveOverlap > 0.05) {
    throw new Error(
      `Hard and standard pack overlap is unexpectedly high: public ${Math.round(publicOverlap * 100)}%, public layouts ${publicLayoutOverlap}, reserve ${Math.round(
        reserveOverlap * 100
      )}%`
    );
  }
}

function formatTime(seconds: number): string {
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`;
}

function summarizePack(label: string, puzzles: LibertiesPuzzle[]): string[] {
  const packAudit = getLibertiesPackAudit(puzzles);
  const standardSeconds = puzzles
    .filter((puzzle) => puzzle.difficulty === 'Standard')
    .map((puzzle) => puzzle.targetSeconds)
    .sort((a, b) => a - b);

  return [
    `## ${label}`,
    '',
    `Puzzles: ${packAudit.puzzleCount}`,
    `Difficulty mix: Easy ${packAudit.difficultyCounts.Easy}, Standard ${packAudit.difficultyCounts.Standard}, Hard ${packAudit.difficultyCounts.Hard}`,
    `Target moves: min ${packAudit.minTargetMoves}, max ${packAudit.maxTargetMoves}, average ${packAudit.averageTargetMoves.toFixed(1)}`,
    `Minimum moves: min ${packAudit.minMinimumMoves}, max ${packAudit.maxMinimumMoves}, average ${packAudit.averageMinimumMoves.toFixed(1)}`,
    `Median target time: ${formatTime(packAudit.medianTargetSeconds)}`,
    `Standard median target time: ${formatTime(packAudit.standardMedianTargetSeconds)}`,
    `Standard target time range: ${formatTime(standardSeconds[0] ?? 0)} - ${formatTime(standardSeconds.at(-1) ?? 0)}`,
    `Average red blockers: ${packAudit.averageBlockerCount.toFixed(1)}`,
    `Average blocker impact: ${packAudit.averageBlockerImpactScore.toFixed(1)}`,
    `Minimum blocker impact: ${packAudit.minimumBlockerImpactScore}`,
    `Average small-board density: ${packAudit.averageSmallBoardDensityScore.toFixed(1)}`,
    `Average decision points: ${packAudit.averageDecisionPointCount.toFixed(1)}`,
    `Average tempo clears: ${packAudit.averageTempoClearCount.toFixed(1)}`,
    `Average stretch pressure: ${packAudit.averageStretchPressureCount.toFixed(1)}`,
    `Average naive penalty: ${packAudit.averageNaivePenalty.toFixed(1)}`,
    `Average terrain usefulness: ${packAudit.averageTerrainUsefulnessScore.toFixed(1)}`,
    `Response events: ${packAudit.responseEventCount}`,
    `Dynamic moves: ${packAudit.dynamicMoveCount}`,
    `Average filler ratio: ${(packAudit.averageFillerMoveRatio * 100).toFixed(1)}%`,
    `Pure fill puzzles: ${packAudit.pureOpeningFillCount}`,
    '',
  ];
}

function writeAuditReport(
  standardResult: LibertiesPackGenerationResult,
  hardResult: LibertiesPackGenerationResult
): void {
  const publicAudit = getLibertiesPackAudit(standardResult.publicPuzzles);
  const strongest = [...standardResult.allPuzzles]
    .map((puzzle) => ({ puzzle, audit: getLibertiesPuzzleAudit(puzzle) }))
    .sort(
      (a, b) =>
        b.audit.captureOrderDependencyScore - a.audit.captureOrderDependencyScore ||
        b.audit.responseEventCount - a.audit.responseEventCount
    )
    .slice(0, 8);

  const strongestHard = [...hardResult.allPuzzles]
    .map((puzzle) => ({ puzzle, audit: getLibertiesPuzzleAudit(puzzle) }))
    .sort(
      (a, b) =>
        b.audit.captureOrderDependencyScore - a.audit.captureOrderDependencyScore ||
        b.audit.responseEventCount - a.audit.responseEventCount
    )
    .slice(0, 8);

  writeFileSync(
    AUDIT_PATH,
    [
      '# Liberties Pack Audit',
      '',
      `Generated standard pool: ${standardResult.allPuzzles.length}`,
      `Standard public daily boards: ${standardResult.publicPuzzles.length}`,
      `Standard reserve boards: ${standardResult.reservePuzzles.length}`,
      `Generated hard pool: ${hardResult.allPuzzles.length}`,
      `Hard public daily boards: ${hardResult.publicPuzzles.length}`,
      `Hard reserve boards: ${hardResult.reservePuzzles.length}`,
      `Standard auto-retune preset: ${standardResult.report.tuningId}`,
      `Standard auto-retune iterations: ${standardResult.report.iterationCount}`,
      `Hard auto-retune preset: ${hardResult.report.tuningId}`,
      `Hard auto-retune iterations: ${hardResult.report.iterationCount}`,
      `Scored candidates: ${standardResult.report.candidateCount}`,
      '',
      ...summarizePack('Standard Public Pack', standardResult.publicPuzzles),
      ...summarizePack('Standard Reserve Pack', standardResult.reservePuzzles),
      ...summarizePack('Standard Combined Pack', standardResult.allPuzzles),
      ...summarizePack('Hard Public Pack', hardResult.publicPuzzles),
      ...summarizePack('Hard Reserve Pack', hardResult.reservePuzzles),
      ...summarizePack('Hard Combined Pack', hardResult.allPuzzles),
      '## Public Terrain Archetypes',
      '',
      ...Object.entries(publicAudit.terrainArchetypeCounts).map(([archetype, count]) => `- ${archetype}: ${count}`),
      '',
      '## Strongest Standard Chase Samples',
      '',
      ...strongest.map(
        ({ puzzle, audit }) =>
          `- ${puzzle.id}: ${puzzle.difficulty}, ${puzzle.targetMoves} moves, ${audit.responseEventCount} stretches, dependency ${audit.captureOrderDependencyScore}`
      ),
      '',
      '## Strongest Hard Chase Samples',
      '',
      ...strongestHard.map(
        ({ puzzle, audit }) =>
          `- ${puzzle.id}: ${puzzle.difficulty}, ${puzzle.targetMoves} moves, ${audit.responseEventCount} stretches, dependency ${audit.captureOrderDependencyScore}`
      ),
      '',
    ].join('\n')
  );
}

console.time('hard generation');
let hardResult = buildLibertiesPacksForGeneration('hard');
console.timeEnd('hard generation');
console.time('standard generation');
const standardResult = buildLibertiesPacksForGeneration('standard', {
  excludedPublicLayouts: new Set(hardResult.allPuzzles.map((puzzle) => puzzle.layout.join('/'))),
  excludedPublicIds: new Set(hardResult.allPuzzles.map((puzzle) => puzzle.id)),
});
console.timeEnd('standard generation');
console.time('hard calendar separation');
const separatedHardPublic = separateHardCompanionCalendar(standardResult.publicPuzzles, hardResult.publicPuzzles);
hardResult = {
  ...hardResult,
  publicPuzzles: separatedHardPublic,
  allPuzzles: [...separatedHardPublic, ...hardResult.reservePuzzles],
};
console.timeEnd('hard calendar separation');
assertHardAndStandardSeparation(
  standardResult.publicPuzzles,
  standardResult.reservePuzzles,
  hardResult.publicPuzzles,
  hardResult.reservePuzzles
);
writeGeneratedPack(
  standardResult.publicPuzzles,
  standardResult.reservePuzzles,
  hardResult.publicPuzzles,
  hardResult.reservePuzzles
);
writeAuditReport(standardResult, hardResult);

const standardAudit = getLibertiesPackAudit(standardResult.publicPuzzles);
const hardAudit = getLibertiesPackAudit(hardResult.publicPuzzles);
const standardCount = standardResult.publicPuzzles.length + standardResult.reservePuzzles.length;
const hardCount = hardResult.publicPuzzles.length + hardResult.reservePuzzles.length;
console.log(`Generated standard pool: ${standardCount} Liberties puzzles`);
console.log(`Standard public boards: ${standardResult.publicPuzzles.length}`);
console.log(`Standard reserve boards: ${standardResult.reservePuzzles.length}`);
console.log(
  `Standard difficulty mix: Easy ${standardAudit.difficultyCounts.Easy}, Standard ${standardAudit.difficultyCounts.Standard}, Hard ${standardAudit.difficultyCounts.Hard}`
);
console.log(`Standard median target seconds: ${standardAudit.standardMedianTargetSeconds}`);
console.log(`Standard median all-target seconds: ${standardAudit.medianTargetSeconds}`);
console.log(`Standard auto-retune preset: ${standardResult.report.tuningId}`);
console.log(`Generated hard pool: ${hardCount} Liberties puzzles`);
console.log(`Hard public boards: ${hardResult.publicPuzzles.length}`);
console.log(`Hard reserve boards: ${hardResult.reservePuzzles.length}`);
console.log(
  `Hard difficulty mix: Easy ${hardAudit.difficultyCounts.Easy}, Standard ${hardAudit.difficultyCounts.Standard}, Hard ${hardAudit.difficultyCounts.Hard}`
);
console.log(`Hard median target seconds: ${hardAudit.medianTargetSeconds}`);
console.log(`Hard auto-retune preset: ${hardResult.report.tuningId}`);
console.log(`Wrote ${GENERATED_PATH}`);
console.log(`Wrote ${AUDIT_PATH}`);
