import { writeFileSync } from 'node:fs';
import {
  buildLibertiesDualPacksForGeneration,
  getLibertiesPackAudit,
  getLibertiesPuzzleAudit,
  type LibertiesDualModePackGenerationResult,
  type LibertiesPuzzle,
  type LibertiesPackGenerationResult,
} from '../src/data/libertiesPuzzles';

const GENERATED_PATH = 'src/data/libertiesPack.generated.ts';
const AUDIT_PATH = 'docs/liberties-pack-audit.md';

function serializePuzzle(puzzle: LibertiesPuzzle): string {
  return JSON.stringify(puzzle, null, 2)
    .replace(/"([a-zA-Z0-9_]+)":/g, '$1:')
    .replace(/\n/g, '\n  ');
}

function serializePuzzleArray(name: string, puzzles: LibertiesPuzzle[]): string {
  const body = puzzles.map((puzzle) => `  ${serializePuzzle(puzzle)}`).join(',\n');
  return [`export const ${name}: LibertiesPuzzle[] = [`, body, '];'].join('\n');
}

function writeGeneratedPack(
  publicPuzzles: LibertiesPuzzle[],
  reservePuzzles: LibertiesPuzzle[],
  hardPublicPuzzles: LibertiesPuzzle[],
  hardReservePuzzles: LibertiesPuzzle[]
): void {
  writeFileSync(
    GENERATED_PATH,
    [
      "import type { LibertiesPuzzle } from './libertiesPuzzles';",
      '',
      '// Generated by `npm run build:liberties-pack`.',
      '// Do not edit individual entries by hand; update the generator/audits instead.',
      serializePuzzleArray('generatedLibertiesPack', publicPuzzles),
      '',
      serializePuzzleArray('generatedLibertiesReservePack', reservePuzzles),
      '',
      serializePuzzleArray('generatedLibertiesHardPack', hardPublicPuzzles),
      '',
      serializePuzzleArray('generatedLibertiesHardReservePack', hardReservePuzzles),
      '',
    ].join('\n')
  );
}

function formatTime(seconds: number): string {
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`;
}

function summarizePack(label: string, puzzles: LibertiesPuzzle[]): string[] {
  const packAudit = getLibertiesPackAudit(puzzles);
  const standardSeconds = puzzles
    .filter((puzzle) => puzzle.difficulty === 'Standard')
    .map((puzzle) => puzzle.targetSeconds)
    .sort((a, b) => a - b);

  return [
    `## ${label}`,
    '',
    `Puzzles: ${packAudit.puzzleCount}`,
    `Difficulty mix: Easy ${packAudit.difficultyCounts.Easy}, Standard ${packAudit.difficultyCounts.Standard}, Hard ${packAudit.difficultyCounts.Hard}`,
    `Generated route moves: min ${packAudit.minTargetMoves}, max ${packAudit.maxTargetMoves}, average ${packAudit.averageTargetMoves.toFixed(1)}`,
    `Move floor: min ${packAudit.minMinimumMoves}, max ${packAudit.maxMinimumMoves}, average ${packAudit.averageMinimumMoves.toFixed(1)}`,
    `Generated-to-floor gap: average ${packAudit.averageTargetToMinimumMoveGap.toFixed(1)}, max ${packAudit.maxTargetToMinimumMoveGap}`,
    `Standard median target time: ${formatTime(packAudit.standardMedianTargetSeconds)}`,
    `Standard target time range: ${formatTime(standardSeconds[0] ?? 0)} - ${formatTime(standardSeconds.at(-1) ?? 0)}`,
    `Average red blockers: ${packAudit.averageBlockerCount.toFixed(1)}`,
    `Average blocker impact: ${packAudit.averageBlockerImpactScore.toFixed(1)}`,
    `Minimum blocker impact: ${packAudit.minimumBlockerImpactScore}`,
    `Average small-board density: ${packAudit.averageSmallBoardDensityScore.toFixed(1)}`,
    `Response events: ${packAudit.responseEventCount}`,
    `Dynamic moves: ${packAudit.dynamicMoveCount}`,
    `Average filler ratio: ${(packAudit.averageFillerMoveRatio * 100).toFixed(1)}%`,
    `Pure fill puzzles: ${packAudit.pureOpeningFillCount}`,
    '',
  ];
}

function summarizeMode(label: string, result: LibertiesPackGenerationResult): string[] {
  const publicAudit = getLibertiesPackAudit(result.publicPuzzles);
  const strongest = [...result.allPuzzles]
    .map((puzzle) => ({ puzzle, audit: getLibertiesPuzzleAudit(puzzle) }))
    .sort(
      (a, b) =>
        b.audit.captureOrderDependencyScore - a.audit.captureOrderDependencyScore ||
        b.audit.responseEventCount - a.audit.responseEventCount
    )
    .slice(0, 8);

  return [
    `## ${label}`,
    '',
    ...summarizePack('Public Daily Pack', result.publicPuzzles),
    ...summarizePack('Reserve Pack', result.reservePuzzles),
    ...summarizePack('Combined 420-Board Pool', result.allPuzzles),
    `Auto-retune preset: ${result.report.tuningId}`,
    `Auto-retune iterations: ${result.report.iterationCount}`,
    `Scored candidates: ${result.report.candidateCount}`,
    '',
    `## ${label} Public Terrain Archetypes`,
    '',
    ...Object.entries(publicAudit.terrainArchetypeCounts).map(([archetype, count]) => `- ${archetype}: ${count}`),
    '',
    '## Strongest Chase Samples',
    '',
    ...strongest.map(
      ({ puzzle, audit }) =>
        `- ${puzzle.id}: ${puzzle.difficulty}, ${puzzle.targetMoves} generated moves, ${puzzle.minMoves ?? puzzle.targetMoves} floor moves, ${audit.responseEventCount} stretches, dependency ${audit.captureOrderDependencyScore}`
    ),
    '',
  ];
}

function countOverlappingPuzzleIds(
  first: LibertiesPuzzle[],
  second: LibertiesPuzzle[]
): { overlapCount: number; overlapRatio: number } {
  const secondIds = new Set(second.map((puzzle) => puzzle.id));
  const overlapCount = first.filter((puzzle) => secondIds.has(puzzle.id)).length;
  const overlapRatio = first.length === 0 ? 0 : overlapCount / first.length;
  return { overlapCount, overlapRatio };
}

function assertHardPackDivergence(
  standard: LibertiesPackGenerationResult,
  hard: LibertiesPackGenerationResult
): void {
  const publicMatch = JSON.stringify(standard.publicPuzzles) === JSON.stringify(hard.publicPuzzles);
  const reserveMatch = JSON.stringify(standard.reservePuzzles) === JSON.stringify(hard.reservePuzzles);
  if (publicMatch && reserveMatch) {
    throw new Error('Hard pack generation produced an output identical to standard in both public and reserve.');
  }

  const publicOverlap = countOverlappingPuzzleIds(hard.publicPuzzles, standard.publicPuzzles);
  const reserveOverlap = countOverlappingPuzzleIds(hard.reservePuzzles, standard.reservePuzzles);
  if (publicOverlap.overlapRatio >= 0.75 || reserveOverlap.overlapRatio >= 0.75) {
    throw new Error(
      `Hard pack output overlaps too much with standard: public ${publicOverlap.overlapCount}/${hard.publicPuzzles.length} `
      + `(${(publicOverlap.overlapRatio * 100).toFixed(1)}%), reserve ${reserveOverlap.overlapCount}/${hard.reservePuzzles.length} `
      + `(${(reserveOverlap.overlapRatio * 100).toFixed(1)}%)`
    );
  }
}

function writeAuditReport(standard: LibertiesPackGenerationResult, hard: LibertiesPackGenerationResult): void {
  const combinedStandard = summarizeMode('Standard-mode Pack', standard);
  const combinedHard = summarizeMode('Hard-mode Pack', hard);

  writeFileSync(
    AUDIT_PATH,
    [
      '# Liberties Pack Audit',
      '',
      ...combinedStandard,
      ...combinedHard,
    ].join('\n')
  );
}

const result: LibertiesDualModePackGenerationResult = buildLibertiesDualPacksForGeneration();
const standard = result.standard;
const hard = result.hard;
assertHardPackDivergence(standard, hard);
const puzzles = standard.publicPuzzles;
writeGeneratedPack(
  standard.publicPuzzles,
  standard.reservePuzzles,
  hard.publicPuzzles,
  hard.reservePuzzles
);
writeAuditReport(standard, hard);

const standardAudit = getLibertiesPackAudit(standard.publicPuzzles);
const hardAudit = getLibertiesPackAudit(hard.publicPuzzles);
console.log(`Generated ${standard.allPuzzles.length + hard.allPuzzles.length} Liberties puzzles`);
console.log(`Standard public: ${standard.publicPuzzles.length}, reserve: ${standard.reservePuzzles.length}`);
console.log(`Hard public: ${hard.publicPuzzles.length}, reserve: ${hard.reservePuzzles.length}`);
console.log(
  `Standard difficulty mix: Easy ${standardAudit.difficultyCounts.Easy}, Standard ${standardAudit.difficultyCounts.Standard}, Hard ${standardAudit.difficultyCounts.Hard}`
);
console.log(
  `Hard difficulty mix: Easy ${hardAudit.difficultyCounts.Easy}, Standard ${hardAudit.difficultyCounts.Standard}, Hard ${hardAudit.difficultyCounts.Hard}`
);
console.log(`Standard median target seconds: ${standardAudit.standardMedianTargetSeconds}`);
console.log(`Hard median target seconds: ${hardAudit.standardMedianTargetSeconds}`);
console.log(`Auto-retune preset: ${standard.report.tuningId}`);
console.log(`Wrote ${GENERATED_PATH}`);
console.log(`Wrote ${AUDIT_PATH}`);
