import { writeFileSync } from 'node:fs';
import {
  buildLibertiesPacksForGeneration,
  getLibertiesPackAudit,
  getLibertiesPuzzleAudit,
  type LibertiesPuzzle,
  type LibertiesPackGenerationResult,
} from '../src/data/libertiesPuzzles';

const GENERATED_PATH = 'src/data/libertiesPack.generated.ts';
const AUDIT_PATH = 'docs/liberties-pack-audit.md';

function serializePuzzle(puzzle: LibertiesPuzzle): string {
  return JSON.stringify(puzzle, null, 2)
    .replace(/"([a-zA-Z0-9_]+)":/g, '$1:')
    .replace(/\n/g, '\n  ');
}

function serializePuzzleArray(name: string, puzzles: LibertiesPuzzle[]): string {
  const body = puzzles.map((puzzle) => `  ${serializePuzzle(puzzle)}`).join(',\n');
  return [`export const ${name}: LibertiesPuzzle[] = [`, body, '];'].join('\n');
}

function writeGeneratedPack(publicPuzzles: LibertiesPuzzle[], reservePuzzles: LibertiesPuzzle[]): void {
  writeFileSync(
    GENERATED_PATH,
    [
      "import type { LibertiesPuzzle } from './libertiesPuzzles';",
      '',
      '// Generated by `npm run build:liberties-pack`.',
      '// Do not edit individual entries by hand; update the generator/audits instead.',
      serializePuzzleArray('generatedLibertiesPack', publicPuzzles),
      '',
      serializePuzzleArray('generatedLibertiesReservePack', reservePuzzles),
      '',
    ].join('\n')
  );
}

function formatTime(seconds: number): string {
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`;
}

function summarizePack(label: string, puzzles: LibertiesPuzzle[]): string[] {
  const packAudit = getLibertiesPackAudit(puzzles);
  const standardSeconds = puzzles
    .filter((puzzle) => puzzle.difficulty === 'Standard')
    .map((puzzle) => puzzle.targetSeconds)
    .sort((a, b) => a - b);

  return [
    `## ${label}`,
    '',
    `Puzzles: ${packAudit.puzzleCount}`,
    `Difficulty mix: Easy ${packAudit.difficultyCounts.Easy}, Standard ${packAudit.difficultyCounts.Standard}, Hard ${packAudit.difficultyCounts.Hard}`,
    `Target moves: min ${packAudit.minTargetMoves}, max ${packAudit.maxTargetMoves}, average ${packAudit.averageTargetMoves.toFixed(1)}`,
    `Standard median target time: ${formatTime(packAudit.standardMedianTargetSeconds)}`,
    `Standard target time range: ${formatTime(standardSeconds[0] ?? 0)} - ${formatTime(standardSeconds.at(-1) ?? 0)}`,
    `Average red blockers: ${packAudit.averageBlockerCount.toFixed(1)}`,
    `Average blocker impact: ${packAudit.averageBlockerImpactScore.toFixed(1)}`,
    `Minimum blocker impact: ${packAudit.minimumBlockerImpactScore}`,
    `Average small-board density: ${packAudit.averageSmallBoardDensityScore.toFixed(1)}`,
    `Response events: ${packAudit.responseEventCount}`,
    `Dynamic moves: ${packAudit.dynamicMoveCount}`,
    `Average filler ratio: ${(packAudit.averageFillerMoveRatio * 100).toFixed(1)}%`,
    `Pure fill puzzles: ${packAudit.pureOpeningFillCount}`,
    '',
  ];
}

function writeAuditReport(result: LibertiesPackGenerationResult): void {
  const publicAudit = getLibertiesPackAudit(result.publicPuzzles);
  const strongest = [...result.allPuzzles]
    .map((puzzle) => ({ puzzle, audit: getLibertiesPuzzleAudit(puzzle) }))
    .sort(
      (a, b) =>
        b.audit.captureOrderDependencyScore - a.audit.captureOrderDependencyScore ||
        b.audit.responseEventCount - a.audit.responseEventCount
    )
    .slice(0, 8);

  writeFileSync(
    AUDIT_PATH,
    [
      '# Liberties Pack Audit',
      '',
      `Generated pool: ${result.allPuzzles.length}`,
      `Public daily boards: ${result.publicPuzzles.length}`,
      `Reserve boards: ${result.reservePuzzles.length}`,
      `Auto-retune preset: ${result.report.tuningId}`,
      `Auto-retune iterations: ${result.report.iterationCount}`,
      `Scored candidates: ${result.report.candidateCount}`,
      '',
      ...summarizePack('Public Daily Pack', result.publicPuzzles),
      ...summarizePack('Reserve Pack', result.reservePuzzles),
      ...summarizePack('Combined 400-Board Pool', result.allPuzzles),
      '## Public Terrain Archetypes',
      '',
      ...Object.entries(publicAudit.terrainArchetypeCounts).map(([archetype, count]) => `- ${archetype}: ${count}`),
      '',
      '## Strongest Chase Samples',
      '',
      ...strongest.map(
        ({ puzzle, audit }) =>
          `- ${puzzle.id}: ${puzzle.difficulty}, ${puzzle.targetMoves} moves, ${audit.responseEventCount} stretches, dependency ${audit.captureOrderDependencyScore}`
      ),
      '',
    ].join('\n')
  );
}

const result = buildLibertiesPacksForGeneration();
const puzzles = result.publicPuzzles;
writeGeneratedPack(result.publicPuzzles, result.reservePuzzles);
writeAuditReport(result);

const audit = getLibertiesPackAudit(puzzles);
console.log(`Generated ${result.allPuzzles.length} Liberties puzzles`);
console.log(`Public daily boards: ${result.publicPuzzles.length}`);
console.log(`Reserve boards: ${result.reservePuzzles.length}`);
console.log(
  `Difficulty mix: Easy ${audit.difficultyCounts.Easy}, Standard ${audit.difficultyCounts.Standard}, Hard ${audit.difficultyCounts.Hard}`
);
console.log(`Standard median target seconds: ${audit.standardMedianTargetSeconds}`);
console.log(`Auto-retune preset: ${result.report.tuningId}`);
console.log(`Wrote ${GENERATED_PATH}`);
console.log(`Wrote ${AUDIT_PATH}`);
