import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  THREADLINE_DATED_SCHEDULE,
  THREADLINE_PUZZLE_BANK,
  THREADLINE_RESERVES,
} from '../src/data/threadlineShippedPack.ts';
import type { ThreadlineCoord, ThreadlinePuzzle } from '../src/data/threadlinePuzzles.ts';

const outputPath = fileURLToPath(
  new URL('../src/data/threadlineRuntimePackData.ts', import.meta.url)
);

const readyReserveIds = THREADLINE_RESERVES
  .filter((reserve) => reserve.reserveStatus === 'ready')
  .map((reserve) => reserve.puzzleId);

const puzzleIndexById = new Map(
  THREADLINE_PUZZLE_BANK.map((puzzle, index) => [puzzle.id, index])
);

const encodePath = (path: ThreadlineCoord[]): string =>
  path.map((coord) => `${coord.row}${coord.col}`).join('');

const compactPuzzle = (puzzle: ThreadlinePuzzle) => [
  puzzle.id,
  puzzle.title,
  puzzle.deck,
  puzzle.difficulty,
  puzzle.grid.join(''),
  puzzle.lead.map((segment) =>
    segment.type === 'text' ? ['t', segment.text] : ['b', segment.wordId]
  ),
  puzzle.threads.map((thread) => [thread.id, thread.name, thread.clue]),
  puzzle.words.map((word) => [
    word.id,
    word.answer,
    word.threadId,
    word.hint,
    encodePath(word.path),
  ]),
  puzzle.weave,
  puzzle.note,
];

const datedScheduleIndexes = THREADLINE_DATED_SCHEDULE.map((entry) => {
  const index = puzzleIndexById.get(entry.puzzleId);
  if (index === undefined) {
    throw new Error(`Missing runtime puzzle index for dated puzzle ${entry.puzzleId}`);
  }
  return [entry.dateKey, index];
});

const readyReserveIndexes = readyReserveIds.map((puzzleId) => {
  const index = puzzleIndexById.get(puzzleId);
  if (index === undefined) {
    throw new Error(`Missing runtime puzzle index for reserve puzzle ${puzzleId}`);
  }
  return index;
});

const contents = `// Generated by scripts/build_threadline_runtime_pack.ts.
// This keeps the player-facing Threadline route from running the editorial/grid generator at startup.

export const THREADLINE_RUNTIME_COMPACT_PUZZLES = ${JSON.stringify(THREADLINE_PUZZLE_BANK.map(compactPuzzle))} as const;

export const THREADLINE_RUNTIME_DATED_INDEXES = ${JSON.stringify(datedScheduleIndexes)} as const;

export const THREADLINE_RUNTIME_READY_RESERVE_INDEXES = ${JSON.stringify(readyReserveIndexes)} as const;
`;

writeFileSync(outputPath, contents);

console.log(
  `Wrote ${THREADLINE_PUZZLE_BANK.length} Threadline runtime puzzles, ` +
    `${THREADLINE_DATED_SCHEDULE.length} dated slots, and ${readyReserveIds.length} ready reserves.`
);
